# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fe3e1686ddb94b64b14ba29034e69bb00a5929cac44f21af4e914c4d4240ab0716571b9a97fca258c30583016eada5e190bc9f320c5fff53b4a3992900f087ed

test:
  secret_key_base: e27ade32ac79236a4a4f423cf4282818f3b8fbbe9d627d708b886056298c76e9cc17c0234c0aab711273d00fe9ef9a821d6cd8c1f500772ec984c5f2a1f71bff

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
